site_name: atools (Job array tools) documentation
site_description: atools is a set of utilities for using job arrays in a very convenient way.
site_author: Geert Jan Bex
pages:
- Introduction and motivation: 'index.md'
- Getting your parameters: 'aenv.md'
- Logging for fun and profit: 'alog.md'
- Resuming tasks and monitoring jobs: 'arange.md'
- Detailed job statistics: 'aload.md'
- Contact and support: 'contact.md'
- FAQ: 'faq.md'
- Change log: 'changes.md'
site_dir: html_docs/atools
theme: readthedocs
